version: "3.8"

services:
  vault:
    image: 'vault:1.13.3'
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=[root]
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - '8200:8200'
    volumes:
      - '/shared_docker/vault/file:/vault/file'
      #- './vault/logs:/vault/logs'
    networks:
      - vault-net

networks:
  vault-net:
    driver: overlay
